[tool.poetry]
name = "django-quill-editor"
version = "0.1.0"
description = ""
authors = ["이한영 <dev@lhy.kr>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.0.3"
django-extensions = "^2.2.8"
django-js-asset = "^1.2.2"
twine = "^3.1.1"
setuptools = "^45.2.0"
wheel = "^0.34.2"

[tool.poetry.dev-dependencies]
notebook = "^6.0.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
